org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.145
neo_version_range=[21.1.145,21.2)
loader_version_range=[1,)

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=levanilla_tacztps
mod_name=TaCZ: Leawind TPS Compat
mod_license=GPL-3.0-only
mod_version=3.0.0-mc1.21.1-neoforge
mod_group_id=com.levanilla
mod_authors=levanilla, airoucat
mod_description=Client-side third-person shooting compatibility layer for MUKSC TaCZ 1.21.1 NeoForge and Leawind's Third Person.

tacz_jar=libs/tacz-neoforge-1.21.1-1.1.7-hotfix-r5.jar
leawind_jar=libs/leawind-third-person-2.3.0-mc1.21-1.21.1-neoforge.jar
architectury_jar=libs/architectury-api-13.0.8-neoforge.jar
