modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="tacz"
type="required"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="leawind_third_person"
type="required"
versionRange="[2.3.0,2.4.0)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="architectury"
type="required"
versionRange="[13.0.8,14.0.0)"
ordering="AFTER"
side="CLIENT"
